apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "web-app.name" . }}
  ports:
    - port: 80
      targetPort: 80
